# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eescalei <eescalei@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 17:38:20 by eescalei          #+#    #+#              #
#    Updated: 2024/02/12 17:41:20 by eescalei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = minishell

CFLAGS = cc -Wall -Wextra -Werror
SRC = main.c

SRC = $(addprefix src/, $(SRC))
OBJ = $(SRC:.c=.o)

all: $(NAME)
	make -C ./inc/pipex/